name: Github Action with a cronjob trigger
on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  cronjob-based-github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
    - name: Check
      run: |
          sudo chmod  +x start.sh
          sudo ./start.sh
